### ISSUE TITLE
pax-web-jetty doesn't support SSL anymore [PAXWEB-898]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1182]
**[JanB](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ddc90d61-e5c1-49ea-b79b-23ad5b6f03d1)** created **[PAXWEB-898](https://ops4j1.jira.com/browse/PAXWEB-898)** 

SSL / TLS support worked correctly in version 2.1.2 of pax-web. However when upgrading to version 4.2.1 it stopped working with the following exception:

```java
2015-10-22T11:15:37,959+0200 [pool-63-thread-1] ERROR Activator - Unable to start pax web server: javax/net/ssl/TrustManager - User= - Batch= - TransactionID=
java.lang.NoClassDefFoundError: javax/net/ssl/TrustManager
	at org.ops4j.pax.web.service.jetty.internal.JettyFactoryImpl.createSecureConnector(JettyFactoryImpl.java:181)
	at org.ops4j.pax.web.service.jetty.internal.JettyFactoryImpl.createSecureConnector(JettyFactoryImpl.java:44)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl$Stopped.start(ServerControllerImpl.java:529)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl.start(ServerControllerImpl.java:71)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl$Unconfigured.configure(ServerControllerImpl.java:700)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl.configure(ServerControllerImpl.java:87)
	at org.ops4j.pax.web.service.internal.Activator.updateController(Activator.java:351)
	at org.ops4j.pax.web.service.internal.Activator$3.run(Activator.java:293)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.net.ssl.TrustManager not found by org.ops4j.pax.web.pax-web-jetty-bundle [313]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1558)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

This is caused by the removal of some import packages from pax-web-jetty and pax-web-jetty-bundle: javax.net.ssl and javax.security.cert.

---

**Affects:** 4.2.2
**Fixed in:** 4.2.3, 6.0.0
Votes: 0, Watches: 1
