### ISSUE TITLE
Logging isn't as optional as advertised! [PAXWEB-502]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#825]
**[TimothyW](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fc4e0735-7226-4de8-be36-cf7b54449bfa)** created **[PAXWEB-502](https://ops4j1.jira.com/browse/PAXWEB-502)** 

I hit an issue when trying out the latest Pax Web milestone. I am using the Pax Web Jetty Bundle, and have installed the OSGi 4.2 compendium interfaces to fill the config admin dependency.<br /> I then attempt to start my bundle and get the following output:

g! start 5<br /> org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.web.pax-web-jetty-bundle [5](https://ops4j1.jira.com/wiki/display/paxweb/5).<br /> at org.apache.felix.framework.Felix.activateBundle(Felix.java:2184)<br /> at org.apache.felix.framework.Felix.startBundle(Felix.java:2052)<br /> at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)<br /> at org.apache.felix.gogo.command.Basic.start(Basic.java:729)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)<br /> at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)<br /> at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)<br /> at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)<br /> at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)<br /> at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)<br /> at org.apache.felix.gogo.shell.Console.run(Console.java:62)<br /> at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)<br /> at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)<br /> at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)<br /> at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)<br /> at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)<br /> at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)<br /> at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)<br /> at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)<br /> at java.lang.Thread.run(Thread.java:662)<br /> Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory<br /> at org.ops4j.pax.web.service.internal.Activator.&lt;clinit&gt;(Activator.java:103)<br /> at org.ops4j.pax.web.service.jetty.internal.CompositeActivator.&lt;init&gt;(CompositeActivator.java:38)<br /> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br /> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)<br /> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)<br /> at java.lang.reflect.Constructor.newInstance(Constructor.java:513)<br /> at java.lang.Class.newInstance0(Class.java:355)<br /> at java.lang.Class.newInstance(Class.java:308)<br /> at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4318)<br /> at org.apache.felix.framework.Felix.activateBundle(Felix.java:2129)<br /> ... 32 more<br /> Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory not found by org.ops4j.pax.web.pax-web-jetty-bundle [5](https://ops4j1.jira.com/wiki/display/paxweb/5)<br /> at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1500)<br /> at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)<br /> at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1923)<br /> at java.lang.ClassLoader.loadClass(ClassLoader.java:248)<br /> ... 42 more<br /> java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

If I install SLF4J (simple) and try starting again I get:

g! start 5<br /> org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.web.pax-web-jetty-bundle [5](https://ops4j1.jira.com/wiki/display/paxweb/5).<br /> at org.apache.felix.framework.Felix.activateBundle(Felix.java:2184)<br /> at org.apache.felix.framework.Felix.startBundle(Felix.java:2052)<br /> at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)<br /> at org.apache.felix.gogo.command.Basic.start(Basic.java:729)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)<br /> at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)<br /> at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)<br /> at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)<br /> at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)<br /> at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)<br /> at org.apache.felix.gogo.shell.Console.run(Console.java:62)<br /> at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)<br /> at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)<br /> at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)<br /> at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)<br /> at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)<br /> at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)<br /> at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)<br /> at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)<br /> at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)<br /> at java.lang.Thread.run(Thread.java:662)<br /> Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.ops4j.pax.web.service.internal.Activator<br /> at org.ops4j.pax.web.service.jetty.internal.CompositeActivator.&lt;init&gt;(CompositeActivator.java:38)<br /> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br /> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)<br /> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)<br /> at java.lang.reflect.Constructor.newInstance(Constructor.java:513)<br /> at java.lang.Class.newInstance0(Class.java:355)<br /> at java.lang.Class.newInstance(Class.java:308)<br /> at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4318)<br /> at org.apache.felix.framework.Felix.activateBundle(Felix.java:2129)<br /> ... 32 more<br /> java.lang.NoClassDefFoundError: Could not initialize class org.ops4j.pax.web.service.internal.Activator

Clearly the logging isn't quite as optional as the bundle declares it to be!

If I refresh the bundle then everything starts working.

I completely understand why all of the logging packages are optional, which is right, but the code doesn't handle the case where none are available. The code also doesn't dynamically react to a logging framework being added.

There are several possible solutions:

a) Catch the Exception and produce a nicer error message. This doesn't really fix anything, but at least it makes the problem easier for a user to resolve.<br /> b) Change the code to make logging truly optional throughout the application (This might be quite hard!)<br /> c) Make all of the logging imports dynamic imports, also fixing the error message. This way the problem can be resolved without refreshing the pax web bundle.<br /> d) Add a Require-Capability header that requires at least one of the logging packages to be resolved. This will involve writing a long LDAP filter with a lot of OR syntax. This is the "nicest" solution for users because Pax Web fails to resolve without a logging implementation (but can use one of several). This fix will only work on R4.3 and R5 frameworks, but it won't cause additional problems for earlier versions.

There's a similar optionality problem in Apache XBean that prevents the Pax Web Extender from starting up properly. I've raised [https://issues.apache.org/jira/browse/XBEAN-240](https://issues.apache.org/jira/browse/XBEAN-240) to cover it.

---

**Affects:** 3.0.0.M2
**Fixed in:** 3.0.0.M3, 3.0.0
Votes: 0, Watches: 0
